config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  resources :movies
  resources :rates
  resources :comments
  resources :users

  post "/login", to: "users#login"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    movie = Movie.find(params[:movie][:id])
    user = User.find(params[:user][:id])
    @rate = Rate.new(rate_params)
    @rate.user = user
    @rate.movie = movie
    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:score, :movie_id, :user_id)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :rate_score %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id, id: :rate_movie_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :rate_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rates</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Movie</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.score %></td>
        <td><%= rate.movie %></td>
        <td><%= rate.user %></td>
        <td><%= link_to 'Show', rate %></td>
        <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
        <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @rate.score %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @rate.movie %>
</p>

<p>
  <strong>User:</strong>
  <%= @rate.user %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>